project:
  type: website

website:
  title: "Projets fin d'études (LOG et GTI)"
  favicon: images/favicon-32x32.png
  repo-url: https://github.com/fuhrmanator/gtilog795-web
  repo-actions: [issue, edit]
  page-footer: |
    [École de technologie supérieure](https://www.etsmtl.ca/), [Département de génie logiciel et des technologies de l'information](https://www.etsmtl.ca/ets/gouvernance/decanats-et-departements/departement-genie-logiciel-ti)
  navbar:
    background: light
    search: true
    logo: images/logo_ets.svg
    left:
      - href: index.qmd
        text: Processus
      - guidePromoteur.qmd
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    lang: fr-CA
    link-external-icon: true
    title-block-banner: true

filters: 
  - filters/pandoc-quotes.lua
#  - filters/diagram-generator.lua
  - quarto


