project:
  type: website

website:
  title: "Projets fin d'études (LOG et GTI)"
  favicon: images/favicon-32x32.png
  navbar:

    logo: images/logo_ets.svg
    left:
      - href: index.qmd
        text: Processus
      - guidePromoteur.qmd
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    lang: fr-CA
    link-external-icon: true
    title-block-banner: false

filters: 
  - filters/pandoc-quotes.lua
#  - filters/diagram-generator.lua
  - quarto


