project:
  type: website

website:
  title: "Projets fin d'études (LOG et GTI)"
  favicon: images/favicon-32x32.png
  # margin-header: |
  #   ![École de technologie supérieure](images/Logo-ETS_SansTypo_FR_1.png)
  navbar:
    background: light
    search: true
    logo: images/Logo-ETS_SansTypo_FR_1.png
    left:
      - href: index.qmd
        text: Processus
      - guidePromoteur.qmd
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    lang: fr-CA
    link-external-icon: true
    title-block-banner: true

filters: 
  - filters/pandoc-quotes.lua
#  - filters/diagram-generator.lua
  - quarto


