---
title: "Directives pour étudiants et étudiantes de PFE avec C. Fuhrman"
bibliography: biblio.bib
---

# Avant la première rencontre

-   Vous devez avoir lu et compris **le plan de cours**. 😉 C. Fuhrman pourra répondre à toutes vos questions pendant la rencontre.
-   Vous devez avoir déterminé **la personne qui jouera le rôle de chef d'équipe** pour que les choses avancent. Le rôle est expliqué dans le plan de cours.
-   Une personne doit agir comme *architecte logiciel* pour le projet. **L'architecte logiciel se soucie de la structure du code, des bonnes pratiques de développement, etc.** Normalement, cette personne évalue les pull requests (demandes de tirage) dans GitHub, mais elle peut aussi faire des revues de code en personne.
-   Vous devez savoir **les disponibilités générales pour votre équipe**. Il faudra faire des démonstrations de solution à la fin de chaque itération. **Une démonstration aura lieu pendant les heures de travail.**
    -   Le promoteur du projet ainsi que C. Fuhrman (et d'autres personnes qui codirigent le cas échéant) seront présents durant ces démonstrations pour donner une rétroaction sur la solution.
    -   Le chef de l'équipe planifie les dates des démonstrations dans le contexte des itérations et **invite le promoteur, C. Fuhrman et les autres personnes impliquées** par le biais d'un agenda électronique (Outlook, Google, etc.).
    -   **Les rencontres** avec C. Fuhrman ou le promoteur **ne peuvent avoir lieu le soir, durant la pause de midi ou durant la fin de semaine.** 👪
    -   Vous trouverez **les disponibilités de C. Fuhrman** sur sa page web: <http://tiny.cc/cfuhrmanGoogleCal>. Consultez-les avant de lui proposer une rencontre spontanée.
-   Vous devez **créer un espace de collaboration** pour votre équipe.
    -   Vous devez partager des documents, des notes, des fichiers, etc. avec votre équipe et avec C. Fuhrman.
    -   C. Fuhrman **recommande l'utilisation de Teams** et Office 365. C. Fuhrman devra autoriser la demande GUS si vous voulez un espace Teams à part, mais dès qu'on cré une rencontre dans Microsoft Teams, on peut y ajouter des fichiers, des notes, etc.
    -   Office est pratique pour le partage de documents (rapports, etc.).
    -   Vous pouvez aussi utiliser Slack ou Discord (pour clavardage) mais c'est plus de gestion. Sachez que Google Drive n'est plus supporté par le STI pour les activités de premiers cycles.
-   Puisque la plupart des projets encadrés par C. Fuhrman impliquent du développement de logiciels libres, il faudrait **avoir un compte sur GitHub**. C. Fuhrman recommande de configurer votre compte sur GitHub avec votre adresse courriel de l'ÉTS. Cela vous permettra d'avoir des fonctionnalités supplémentaires (Copilot, etc.) grâce à GitHub for Education.
-   Il faut que votre équipe ait discuté de la license libre à utiliser pour votre projet. **C. Fuhrman recommande d'utiliser une license libre comme la license MIT**.
-   Tout PFE ayant une licence libre doit être **hébergé sur GitHub et la licence doit être dans le dépôt**. C. Fuhrman recommande de créer un dépôt pour votre projet sur GitHub dès que possible. **C. Fuhrman refusera de corriger votre rapport si la license n'est pas dans le dépôt.**
-   Il vaut mieux avoir commencé le **contrat d'encadrement disponible sur Moodle**. Suivez un des exemples disponibles également sur Moodle.

# Pour la première rencontre

-   Prévoyez une rencontre d'environ 1 heure, en personne. Vous pouvez réserver un local de rencontre via le portail MonETS.
-   La rencontre peut être séparée en deux parties:
    1. Une partie (~30 minutes) avec C. Fuhrman et les codirecteurs ou codirectrices pour discuter du plan de cours, du contrat d'encadrement, etc.
    2. Une partie avec le promoteur du projet (client) pour discuter du projet, des attentes, etc. Cette partie pourrait être plus longue (30 à 60 minutes) et pourrait être faite à une autre date. Si les deux rencontres sont ensemble, il faut expliquer au promoteur que la première partie de la rencontre ne le concerne pas et qu'il peut arriver plus tard.
-   Préparez une **présentation PowerPoint** (ou autre) pour la rencontre.
-   Envoyez le contrat d'encadrement à C. Fuhrman au moins 24 heures avant la rencontre.

# Pendant le projet itératif

Chaque itération doit être planifiée pour que l'équipe puisse avancer de manière efficace et que les promoteurs puissent fournir une rétroaction sur l'avancement du projet. Voici quelques conseils pour chaque itération:

- L'architecte logiciel doit s'assurer que le code respecte les bonnes pratiques de développement (structure, tests automatisés, documentation, etc.) et que les pull requests sont évaluées avant d'être fusionnées dans la branche principale.
- Pour la planification, utilisez le [gabarit de plan d'itération de LOG210](https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/rapports/plan-iteration-gabarit.md).
  - Les objectifs de l'itération doivent être clairs et mesurables, idéalement des besoins ([FURPS](https://fuhrmanator.github.io/log210-ndc-quarto/Besoins.html#furps)). Évitez de proposer les artefacts de développement comme objectifs, par exemple "~~Écrire le code pour la fonctionnalité X~~" ou "~~Faire la documentation de la fonctionnalité Y~~". Il s'agit de tâches (dans la partie **Affectations d'éléments de travail**), pas d'objectifs.
  - Il faut confirmer les objectifs de l'itération avec le promoteur du projet avant de commencer l'itération.
  - Les **Critères d'évaluation** doivent être clairs et mesurables, idéalement des tests automatisés. Pour les fonctionnalités, on peut aussi les évaluer par un critère d'acceptation, par exemple "La fonctionnalité X a reçu une rétroaction positive de la part du promoteur".
- Créez un plan d'itération pour chaque itération _avant_ le début de l'itération et partagez-le avec C. Fuhrman pour obtenir des commentaires.
- À la mi-itération, faites une rétrospective pour voir si vous pourrez attendre les objectifs de l'itération. Si vous ne pourrez pas, ajustez le plan d'itération (réduire les fonctionnalités, déplacer un objectif à la prochaine itération, etc.).
- Quelques jours avant la fin de l'itération (avant la démonstration), partagez les objectifs du plan d'itération avec les parties prenantes (invitées à la démonstration) pour qu'ils sachent à quoi s'attendre.
- La démonstration doit suivre le plan d'itération. Ne montrez pas des éléments (plan du projet, contrat d'encadrement, etc.) de votre PFE qui ne concernent pas les promoteurs (clients) du système que vous présentez.
- Au moins une personne dans l'équipe doit prendre les notes pendant la démonstration.
- Après la démonstration, compléter la section "Évaluation" du plan (c'est ce que vous auriez dû faire dans LOG210), et planifier les objectifs pour la prochaine itération.
- Dans le cours de gestion de projet de votre programme, vous auriez dû voir des stratégies de planification de projet itératif/agile. Utilisez ces stratégies pour planifier vos itérations.

# Conseils pour la présentation

Ces conseils complémentent les directives de l'Annexe C de @chasse2005preparer.

## Organisation du contenu

- Si vous utilisez PowerPoint, **organisez votre présentation avec l'aperçu "plan" (*outline* en anglais) avant d'ajouter les images**, etc. Saisir le texte de cette manière a aussi l'avantage que l'affichage des diapositives respectera la conception du gabarit (polices, couleurs, etc.).
- Considérez [le logiciel open-source Quarto pour faire votre présentation](https://quarto.org/docs/gallery/#presentations) dont la rédaction se fait en markdown.
Je l'utilise pour faire toutes mes présentations en classe, le manuel de LOG210 et même ce site web de conseils.
- Limitez l'affichage de texte à six ou sept **points** par diapositive, que vous organiserez en liste à puces, par exemple. N'affichez pas plus que six à huit mots par ligne.
- Si vous devez absolument afficher du texte en continu, limitez-vous à des segments de deux ou trois phrases (quatre à six lignes), et prévoyez un temps de lecture approprié pour l'auditoire.
- Vos diapositives devraient inclure divers repères relatifs au déroulement de l'exposé et à la structure de son support visuel. Par exemple, prenez soin de **paginer** vos diapositives. Signalez par un moyen ou un code quelconque où on en est dans le plan de l'exposé :
  - Réaffichez périodiquement le plan en marquant (couleur, encadré, etc.) le point qu'on va aborder.
  - Affichez, dans chaque diapositive, un en-tête ou une icône indiquant le point du plan auquel on se réfère.
- Pour la partie introduction (et contexte), **vulgarisez**!
Vous avez travaillé toute la session sur votre projet et vous le comprenez bien.
Ce n'est pas le cas pour votre publique.
Pour garder l'attention de votre publique, il faut qu'il comprenne bien le problème de votre PFE.
Vous pouvez revenir à l'énoncé de la proposition de PFE (sur le site Moodle du cours) si vous avez besoin d'inspiration, car normalement le problème du projet vous a été expliqué dans ce texte-là.

## Aspects visuels

- **Utilisez un gabarit prédéfini**: cela une palette de couleurs équilibrée et homogène.
-   Utilisez un gabarit avec **les polices lisibles à l'écran dans une salle de classe**.
    Malheureusement, beaucoup de gabarits sont conçus (je crois) pour les présentations en ligne, où le publique est proche de l'écran.
    Vous devez faire la présentation dans une salle de classe avec 30 à 50 places assises.
    Alors, voici mes conseils pour les polices:
    -   Titres et en-têtes: 32-44 points (ou plus).
    -   Text principal: 24-28 points.
    -   Sous-titres ou annotations: 18-20 points.
-   Pour les captures d'écran de page web, **utilisez le zoom du navigateur pour grossir le texte si possible AVANT de faire la capture d'écran**.
-   Si vous avez des graphes ou d'autres visualisations, sachez qu'une police plus petite que 20 points ne sera pas très lisible.
-   **Ne pas utiliser "dark mode"** pour les captures d'écran ou pour afficher du code source; ça s'affiche mal sur les projecteurs.
- **Privilégiez les fonds clairs**: ils conviennent à la plupart des éclairages et facilitent la lecture.
- **Évitez les fonds texturés** (motifs, filigranes, etc.) : ils nuisent à la lisibilité.
- Contrastez bien les couleurs du texte et les autres éléments avec le fond.
- **Limitez-vous à trois couleurs** principales sur l'ensemble de vos diapositives.
- Faites en sorte que l'emploi des couleurs soit cohérent pour les titres, les sous-titres, etc. 

# Conseils pour la rédaction du rapport

Le rapport vaut beaucoup de points, car votre bon travail de PFE sera rayonné par ce document.

-   Éviter le plagiat [Cours : ATE800 Intégrité intellectuelle : un savoir-être et un savoir-faire (HIV2016)](https://accros.etsmtl.ca/Rapports/atelier/index.html)

-   Si vous pensez utiliser un SIAG (Systèmes d'Intelligence Artificielle Générative, comme ChatGPT ou Copilot) pour aider avec la rédaction :

    -   Les informations que vous donnez au SIAG sont souvent réutilisées par l'entreprise (OpenAI, Microsoft, etc.) offrant le service (vous leur donnez des informations)! **Ça peut donc aller à l'encontre de la confidentialité** (surtout pour les **projets où le promoteur est une entreprise**). Il vaut mieux en parler avec le promoteur avant d'utiliser le SIAG.
    -   On **doit** déclarer quels outils SIAG ont été utilisés lors de la rédaction (dans la section Avant-Propos). Sinon, c'est [une infraction de nature académique](https://www.etsmtl.ca/a-propos/gouvernance/secretariat-general/cadre-reglementaire/reglement-sur-les-infractions-de-nature-academique).

-   Utiliser un outil comme Antidote pour éviter les fautes de français.

-   Suivre les directives de rédaction sur [Accros](https://accros.etsmtl.ca/)

    -   [Guides et gabarits de rédaction](http://etsmtl.ca/Etudiants-actuels/Cycles-sup/Realisation-etudes/Guides-gabarits)
        -   Bibliographie, citations
        -   Mendeley, EndNote, Zotero, etc.
        -   Zotero fonctionne avec Word (application Windows) mais pas avec Office 365.

-   Pour le temps des verbes, il faut respecter les consignes du [Guide de rédaction d'un rapport technique](https://accros.etsmtl.ca/rapports/findetudes/rapport_fin_etudes/guide_redaction.pdf#page=16):

    > *1.7 Temps de verbe*
    >
    > *Dans un rapport technique, le choix des temps de verbe se résume à une seule règle quasi générale : **usage exclusif du présent et du passé composé***.

-   Pour la structure, il y a un bon résumé dans **1.3 Développement ou corps du travail** <https://www.etsmtl.ca/docs/etudes/Guides-gabarits/Documents/guide-redaction-projet-memoire-these#page=23>.
    Cependant, la structure est généralisée pour un rapport d'ingénierie.
    Il est normal d'avoir des questions à propos de comment appliquer cette structure à un sujet précis.
    **C'est important de communiquer avec moi tôt par rapport à la structure.**

    -   Pour la partie "Revue de la littérature", on s'attend à ce qu'il y ait une présentation et un résumé des pratiques pertinentes à propos du sujet. Il n'est pas nécessaire de faire une revue exhaustive, mais il faut présenter des éléments importants dans le domaine (livres, articles de revue scientifique, normes, etc.). Généralement il s'agit d'au moins une dizaine de références.
    -   Souvent, la partie "Résultats" se présente sur plusieurs chapitres. Par exemple, dans une application Web, l'équipe a fait des contributions concernant les parties frontale, serveur, base de données, etc. Il vaut mieux les présenter dans des chapitres séparés.

-   Pour la conclusion, je vous recommande la structure suivante en **3 paragraphes**.
    Ceci est un extrait de la grille d'évaluation provenant du site [Accros](https://accros.etsmtl.ca/Rapports/index.asp):

+------------------------------------------------+------------------------------------------------------------------------------+-------------------------+
| Critères                                       | Sous-critère 1                                                               | Sous-critère 2          |
+================================================+==============================================================================+=========================+
| **1^er^ paragraphe \                           | Respect des objectifs                                                        | Respect des normes      |
| Résumé du développement**                      |                                                                              |                         |
|                                                | -   Rappel succinct des éléments de la problématique, des solutions retenues | -   cohérence du propos |
|                                                |                                                                              |                         |
|                                                | -   Souci de guider le lecteur vers la prise de décision                     | -   logique des idées   |
|                                                |                                                                              |                         |
|                                                |                                                                              | -   pertinence du cas   |
+------------------------------------------------+------------------------------------------------------------------------------+-------------------------+
| **2^e^ paragraphe \                            | Démarche explicitée                                                          | Limites du projet       |
| Rappel précis du mandat, de la problématique** |                                                                              |                         |
+------------------------------------------------+------------------------------------------------------------------------------+-------------------------+
| **3^e^ paragraphe\                             | Guider le lecteur vers l'action à entreprendre                               |                         |
| ouverture**                                    |                                                                              |                         |
+------------------------------------------------+------------------------------------------------------------------------------+-------------------------+

# Références
